---
services:  
  crypto_machine:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      labnet:
        ipv4_address: 172.20.0.10
    command: sleep infinity
  
  crypto_machine2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      labnet:
        ipv4_address: 172.20.0.20
  networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24