version: '3.8'
services:
     wireguard:
       image: linuxserver/wireguard
       container_name: wireguard
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=Etc/UTC
         - SERVERURL=172.20.0.10
         - SERVERPORT=51820
         - PEERS=cliente1
         - PEERDNS=auto
         - INTERNAL_SUBNET=10.0.0.0/24
       volumes:
         - ./config:/config
       ports:
         - "51820:51820/udp"
       networks:
         red-proxy:
           ipv4_address: 172.20.0.10
       cap_add:
         - NET_ADMIN
         - SYS_MODULE
       sysctls:
         - net.ipv4.conf.all.src_valid_mark=1
         - net.ipv4.ip_forward=1
       restart: unless-stopped

networks:
  red-proxy:
    external: true